version: '2'

services:
  oracle:
    extends:
      file: ./oracle/docker-compose.yml
      service: oracle
    volumes:
      - oraclelog:/tmp
      - ./oracle/opt:/opt/script

  sqlcl:
    extends:
      file: ./sqlcl/docker-compose.yml
      service: sqlcl

  elasticsearch:
    extends:
      file: ./elasticsearch/docker-compose.yml
      service: elasticsearch

  logstash:
    extends:
      file: ./logstash/docker-compose.yml
      service: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - oraclelog:/mnt/data:rw
    depends_on:
      - elasticsearch

  kibana:
    extends:
      file: ./kibana/docker-compose.yml
      service: kibana
    depends_on:
      - elasticsearch

volumes:
  oraclelog:
  esdata:

networks:
  esnet:
    driver: bridge
