version: '2'

services:
  oracle:
    image: oracle/database:12.2.0.1-ee
    environment:
      ORACLE_SID: ORCLCDB
      ORACLE_PDB: ORCLPDB1
      ORACLE_PWD: manager
    ports:
      - 1521:1521
      - 5500:5500
