select /*json*/
sql_text,
sql_id,
sorts,
version_count,
fetches,
TRUNC(fetches/DECODE(executions,0,1,executions)) "fetches_per_execution",
executions,
loads,
invalidations,
parse_calls,
disk_reads,
TRUNC(disk_reads/DECODE(executions,0,1,executions)) "disk_reads_per_execution",
direct_writes,
buffer_gets,
TRUNC(buffer_gets/DECODE(executions,0,1,executions)) "buffer_gets_per_execution",
application_wait_time,
concurrency_wait_time,
cluster_wait_time,
user_io_wait_time,
plsql_exec_time,
java_exec_time,
rows_processed,
TRUNC(rows_processed/DECODE(executions,0,1,executions)) "rows_processed_per_execution",
serializable_aborts,
cpu_time,
TRUNC(cpu_time/DECODE(executions,0,1,executions)) "cpu_time_per_execution",
elapsed_time,
TRUNC(elapsed_time/DECODE(executions,0,1,executions)) "elapsed_time_per_execution",
to_char(last_active_time,'DD-MM-YYYY HH24:MI:SS') AS last_active_time,
'sqlarea' AS tag
FROM v$sqlstats;
